/// Flutter icons ProIconUI
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProIconUI
///      fonts:
///       - asset: fonts/ProIconUI.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ProIconUI {
  ProIconUI._();

  static const _kFontFam = 'ProIconUI';

  static const IconData back = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData back_fill =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bag_fill =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bell_fill =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData camera_fill =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData close_fill =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData confirm = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData confirm_confirm =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData equalizer =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData equalizer_fill =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData go = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData go_fill = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData grid = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData grid_fill =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData heart_fill =
      const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData home_fill =
      const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData messages =
      const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData messages_fill =
      const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData plus_fill =
      const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData search_fill =
      const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData settings_fill =
      const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData share_fill =
      const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData user_fill =
      const IconData(0xe821, fontFamily: _kFontFam);
}
