/// Flutter icons ProIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProIcons
///      fonts:
///       - asset: fonts/ProIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ProIcons {
  ProIcons._();

  static const _kFontFam = 'ProIcon';

  static const IconData contacts =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData conus = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData desctop = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData drop = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData flashdrive =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData furniture =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData gamepad = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData go = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData grid = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData keyboard =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData lab = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData medecine =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData messages =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData mobile = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData mouse = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData nature = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData planet = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData portfolio =
      const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData washer = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData ball = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData battery = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData cartridge =
      const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData cd = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData cloth = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData coctail = const IconData(0xe825, fontFamily: _kFontFam);
}
